language: python
addons:
  firefox: "52.0.2"
sudo: true
cache:
  directories:
    - eggs
    - downloads
python: 2.7
install:
  - python bootstrap.py --buildout-version=2.7.0
  - bin/buildout -N buildout:download-cache=downloads annotate
  - bin/buildout buildout:download-cache=downloads
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - firefox -v
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.15.0/geckodriver-v0.15.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.15.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
script:
  - bin/code-analysis
  - bin/test
after_success:
  - bin/createcoverage
  - pip install -q coveralls==0.5
  - coveralls
#after_script:
#  # killing background process (because dockerized build no longer does it)
#  - kill -9 $(ps aux | grep 'selenium' | awk '{print $2}')
notifications:
  email:
    recipients:
      - devel@lists.affinitic.be
      - devs@imio.be
    on_success: change
    on_failure: change
