language: python
cache:
  directories:
    - eggs
    - downloads
python: 2.7
install:
  - python bootstrap.py
  - bin/buildout -N buildout:download-cache=downloads annotate
  - bin/buildout -N buildout:download-cache=downloads
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - firefox -v
script:
  - bin/code-analysis
  - bin/test
after_success:
  - bin/createcoverage
  - pip install -q coveralls==0.5
  - coveralls
notifications:
  email:
    recipients:
      - devel@lists.affinitic.be
      - devs@imio.be
    on_success: change
    on_failure: change
